# Generated by Django 4.2.28 on 2026-03-14 18:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pretixbase', '0297_outgoingmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcubeAccessScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('engine', models.CharField(db_index=True, default='unknown', max_length=32)),
                ('object_type', models.CharField(db_index=True, default='unknown', max_length=32)),
                ('raw_payload', models.TextField()),
                ('normalized_code', models.CharField(db_index=True, max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('display_type', models.CharField(max_length=255)),
                ('result', models.CharField(db_index=True, default='pending', max_length=32)),
                ('message', models.TextField()),
                ('gate', models.CharField(max_length=255)),
                ('operator_name', models.CharField(max_length=255)),
                ('device_id', models.CharField(max_length=255)),
                ('response_snapshot', models.JSONField(null=True)),
                ('scanned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecube_access_scan_logs', to='pretixbase.event')),
            ],
            options={
                'ordering': ('-scanned_at',),
                'indexes': [models.Index(fields=['event', 'scanned_at'], name='pretix_ecub_event_i_d9b86d_idx'), models.Index(fields=['event', 'engine'], name='pretix_ecub_event_i_57fc23_idx'), models.Index(fields=['event', 'result'], name='pretix_ecub_event_i_caab4a_idx')],
            },
        ),
    ]

