# Generated by Django 4.2.28 on 2026-03-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_ecube_access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecubeaccessscanlog',
            name='action',
            field=models.CharField(db_index=True, default='entry', max_length=16),
        ),
        migrations.AddIndex(
            model_name='ecubeaccessscanlog',
            index=models.Index(fields=['event', 'action'], name='pretix_ecub_event_i_c7e786_idx'),
        ),
    ]

