# Generated by Django 4.2.28 on 2026-03-14 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0297_outgoingmail'),
        ('pretix_ecube_access', '0002_ecubeaccessscanlog_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcubeAccessDoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80)),
                ('public_token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_action', models.CharField(default='entry', max_length=16)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecube_access_doors', to='pretixbase.event')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('event', 'slug')},
            },
        ),
    ]

