# Generated by Django 4.2.28 on 2026-03-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_admissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='admissioncredential',
            new_name='pretix_admi_event_i_414151_idx',
            old_name='pretix_admi_event_s_80c6f5_idx',
        ),
        migrations.RenameIndex(
            model_name='admissioncredential',
            new_name='pretix_admi_event_i_b1667b_idx',
            old_name='pretix_admi_event_c_9cb0ec_idx',
        ),
        migrations.RenameIndex(
            model_name='admissioncredential',
            new_name='pretix_admi_event_i_0ddff3_idx',
            old_name='pretix_admi_event_c_d628d2_idx',
        ),
        migrations.RenameIndex(
            model_name='admissioncredential',
            new_name='pretix_admi_event_i_875db3_idx',
            old_name='pretix_admi_event_h_f4d8f2_idx',
        ),
        migrations.RenameIndex(
            model_name='admissionscanevent',
            new_name='pretix_admi_event_i_b0172d_idx',
            old_name='pretix_admi_event_s_414839_idx',
        ),
        migrations.RenameIndex(
            model_name='admissionscanevent',
            new_name='pretix_admi_credent_1cc76e_idx',
            old_name='pretix_admi_credent_68e270_idx',
        ),
        migrations.RenameIndex(
            model_name='admissionscanevent',
            new_name='pretix_admi_result_883ec8_idx',
            old_name='pretix_admi_result_4ad16a_idx',
        ),
        migrations.AddField(
            model_name='admissioncredential',
            name='entry_mode',
            field=models.CharField(db_index=True, default='single', max_length=32),
        ),
        migrations.AddField(
            model_name='admissioncredential',
            name='is_inside',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='admissioncredential',
            name='last_entry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissioncredential',
            name='last_exit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionscanevent',
            name='action',
            field=models.CharField(db_index=True, default='entry', max_length=16),
        ),
        migrations.AlterField(
            model_name='admissioncredential',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='admissionscanevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='admissioncredential',
            index=models.Index(fields=['event', 'entry_mode'], name='pretix_admi_event_i_cd062e_idx'),
        ),
        migrations.AddIndex(
            model_name='admissioncredential',
            index=models.Index(fields=['event', 'is_inside'], name='pretix_admi_event_i_30e85b_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionscanevent',
            index=models.Index(fields=['action'], name='pretix_admi_action_6eb8dd_idx'),
        ),
    ]

