# Generated by Django 4.2.28 on 2026-03-14 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pretix_exclusive_access.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pretixbase', '0297_outgoingmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusiveAccessApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=190)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('instagram_handle', models.CharField(max_length=255)),
                ('referred_by', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('photo', models.ImageField(upload_to=pretix_exclusive_access.models.application_photo_upload_to)),
                ('photo_uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('photo_hash', models.CharField(max_length=64)),
                ('identity_photo_locked', models.BooleanField(default=False)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('internal_note', models.TextField()),
                ('voucher_code', models.CharField(max_length=120)),
                ('voucher_id', models.PositiveIntegerField(null=True)),
                ('approved_order_code', models.CharField(max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_order_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusive_access_application', to='pretixbase.orderposition')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_access_applications', to='pretixbase.event')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_access_applications', to='pretixbase.item')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exclusive_access_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event', 'status'], name='pretix_excl_event_i_0f9833_idx'), models.Index(fields=['event', 'email'], name='pretix_excl_event_i_321468_idx')],
                'unique_together': {('event', 'item', 'email')},
            },
        ),
    ]

