# Generated by Django 4.2.28 on 2026-03-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_exclusive_access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusiveaccessapplication',
            name='access_token',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='exclusiveaccessapplication',
            name='access_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='exclusiveaccessapplication',
            index=models.Index(fields=['event', 'access_token'], name='pretix_excl_event_i_43f124_idx'),
        ),
    ]

