# Generated by Django 4.2.28 on 2026-03-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_exclusive_access', '0002_exclusiveaccessapplication_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusiveaccessapplication',
            name='guest_category',
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='exclusiveaccessapplication',
            name='source',
            field=models.CharField(db_index=True, default='public_form', max_length=32),
        ),
        migrations.AddField(
            model_name='exclusiveaccessapplication',
            name='status_reason',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='exclusiveaccessapplication',
            name='internal_note',
            field=models.TextField(default=''),
        ),
    ]

