# Generated by Django 4.2.28 on 2026-03-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_exclusive_access', '0011_exclusiveaccessapplication_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclusiveaccessapplication',
            name='instagram_handle',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='exclusiveaccessapplication',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
