# Generated by Django 4.2.28 on 2026-03-20 10:00

import django.db.models.deletion
import pretix_event_themes.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pretixbase", "0297_outgoingmail"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDesignAssetPack",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hero_original", models.FileField(blank=True, upload_to=pretix_event_themes.models.event_asset_upload_to("hero-original"))),
                ("hero_card_16x9", models.FileField(blank=True, upload_to=pretix_event_themes.models.event_asset_upload_to("hero-card-16x9"))),
                ("hero_email_banner", models.FileField(blank=True, upload_to=pretix_event_themes.models.event_asset_upload_to("hero-email-banner"))),
                ("hero_ticket_texture", models.FileField(blank=True, upload_to=pretix_event_themes.models.event_asset_upload_to("hero-ticket-texture"))),
                ("thumbnail_override", models.FileField(blank=True, upload_to=pretix_event_themes.models.event_asset_upload_to("thumbnail-override"))),
                ("thumbnail_square", models.FileField(blank=True, upload_to=pretix_event_themes.models.event_asset_upload_to("thumbnail-square"))),
                ("logo_original", models.FileField(blank=True, upload_to=pretix_event_themes.models.event_asset_upload_to("logo-original"))),
                ("logo_email", models.FileField(blank=True, upload_to=pretix_event_themes.models.event_asset_upload_to("logo-email"))),
                ("logo_ticket", models.FileField(blank=True, upload_to=pretix_event_themes.models.event_asset_upload_to("logo-ticket"))),
                ("background_texture_original", models.FileField(blank=True, upload_to=pretix_event_themes.models.event_asset_upload_to("background-texture-original"))),
                ("background_texture_web", models.FileField(blank=True, upload_to=pretix_event_themes.models.event_asset_upload_to("background-texture-web"))),
                ("background_texture_ticket", models.FileField(blank=True, upload_to=pretix_event_themes.models.event_asset_upload_to("background-texture-ticket"))),
                ("hero_focal_x", models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ("hero_focal_y", models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ("processing_meta", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="ecube_design_assets", to="pretixbase.event")),
            ],
            options={
                "ordering": ("event_id",),
            },
        ),
    ]
